export const FETCH_RESERVATIONS_REQUEST = "FETCH_RESERVATIONS_REQUEST";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const FETCH_RESERVATIONS_FAILURE = "FETCH_RESERVATIONS_FAILURE";

export const DELETE_RESERVATION_REQUEST = "DELETE_RESERVATION_REQUEST";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_FAILURE = "DELETE_RESERVATION_FAILURE";

export const DELETE_PERIODIC_RESERVATION_REQUEST =
  "DELETE_PERIODIC_RESERVATION_REQUEST";
export const DELETE_PERIODIC_RESERVATION_SUCCESS =
  "DELETE_PERIODIC_RESERVATION_SUCCESS";
export const DELETE_PERIODIC_RESERVATION_FAILURE =
  "DELETE_PERIODIC_RESERVATION_FAILURE";

export const ADD_RESERVATION_REQUEST = "ADD_RESERVATION_REQUEST";
export const ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS";
export const ADD_RESERVATION_FAILURE = "ADD_RESERVATION_FAILURE";

export const GET_RESERVATIONS_BY_DATE_REQUEST =
  "GET_RESERVATIONS_BY_DATE_REQUEST";
export const GET_RESERVATIONS_BY_DATE_SUCCESS =
  "GET_RESERVATIONS_BY_DATE_SUCCESS";
export const GET_RESERVATIONS_BY_DATE_FAILURE =
  "GET_RESERVATIONS_BY_DATE_FAILURE";

export const GET_RESERVATIONS_BY_RESOURCE_REQUEST =
  "GET_RESERVATIONS_BY_RESOURCE_REQUEST";
export const GET_RESERVATIONS_BY_RESOURCE_SUCCESS =
  "GET_RESERVATIONS_BY_RESOURCE_SUCCESS";
export const GET_RESERVATIONS_BY_RESOURCE_FAILURE =
  "GET_RESERVATIONS_BY_RESOURCE_FAILURE";

export const GET_PERIODIC_RESERVATIONS_REQUEST =
  "GET_PERIODIC_RESERVATIONS_REQUEST";
export const GET_PERIODIC_RESERVATIONS_SUCCESS =
  "GET_PERIODIC_RESERVATIONS_SUCCESS";
export const GET_PERIODIC_RESERVATIONS_FAILURE =
  "GET_PERIODIC_RESERVATIONS_FAILURE";

export const GET_USER_RESERVATIONS_REQUEST = "GET_USER_RESERVATIONS_REQUEST";
export const GET_USER_RESERVATIONS_SUCCESS = "GET_USER_RESERVATIONS_SUCCESS";
export const GET_USER_RESERVATIONS_FAILURE = "GET_USER_RESERVATIONS_FAILURE";

export const CHECK_AVAILABILITY_REQUEST = "CHECK_AVAILABILITY_REQUEST";
export const CHECK_AVAILABILITY_SUCCESS = "CHECK_AVAILABILITY_SUCCESS";
export const CHECK_AVAILABILITY_FAILURE = "CHECK_AVAILABILITY_FAILURE";

export const FILL_RESERVATION_FORM = "FILL_RESERVATION_FORM";
export const EMPTY_RESERVATION_FORM = "EMPTY_RESERVATION_FORM";

export const FILL_AVAILABILITY_FORM = "FILL_AVAILABILITY_FORM";
export const EMPTY_AVAILABILITY_FORM = "EMPTY_AVAILABILITY_FORM";

export const EMPTY_AVAILABILITY_RESOUCRES = "EMPTY_AVAILABILITY_RESOUCRES";
