export const GET_BACK_OFFICE_SETTINGS_REQUEST =
  "GET_BACK_OFFICE_SETTINGS_REQUEST";
export const GET_BACK_OFFICE_SETTINGS_SUCCESS =
  "GET_BACK_OFFICE_SETTINGS_SUCCESS";
export const GET_BACK_OFFICE_SETTINGS_FAILURE =
  "GET_BACK_OFFICE_SETTINGS_FAILURE";

export const UPDATE_BACK_OFFICE_SETTINGS_SUCCESS =
  "GET_BACK_OFFICE_SETTINGS_SUCCESS";
export const UPDATE_BACK_OFFICE_SETTINGS_REQUEST =
  "GET_BACK_OFFICE_SETTINGS_REQUEST";
export const UPDATE_BACK_OFFICE_SETTINGS_FAILURE =
  "GET_BACK_OFFICE_SETTINGS_FAILURE";
