export const FETCH_RESSOURCE_TYPES_REQUEST = "FETCH_RESSOURCE_TYPES_REQUEST";
export const FETCH_RESSOURCE_TYPES_SUCCESS = "FETCH_RESSOURCE_TYPES_SUCCESS";
export const FETCH_RESSOURCE_TYPES_FAILURE = "FETCH_RESSOURCE_TYPES_FAILURE";

export const GET_RESSOURCE_TYPES_BY_TYPE_REQUEST = "GET_RESSOURCE_TYPES_BY_TYPE_REQUEST";
export const GET_RESSOURCE_TYPES_BY_TYPE_SUCCESS = "GET_RESSOURCE_TYPES_BY_TYPE_SUCCESS";
export const GET_RESSOURCE_TYPES_BY_TYPE_FAILURE = "GET_RESSOURCE_TYPES_BY_TYPE_FAILURE";

export const UPDATE_RESSOURCE_TYPE_REQUEST = "UPDATE_RESSOURCE_TYPE_REQUEST";
export const UPDATE_RESSOURCE_TYPE_SUCCESS = "UPDATE_RESSOURCE_TYPE_SUCCESS";
export const UPDATE_RESSOURCE_TYPE_FAILURE = "UPDATE_RESSOURCE_TYPE_FAILURE";

export const DELETE_RESSOURCE_TYPE_REQUEST = "DELETE_RESSOURCE_TYPE_REQUEST";
export const DELETE_RESSOURCE_TYPE_SUCCESS = "DELETE_RESSOURCE_TYPE_SUCCESS";
export const DELETE_RESSOURCE_TYPE_FAILURE = "DELETE_RESSOURCE_TYPE_FAILURE";

export const ADD_RESSOURCE_TYPE_REQUEST = "ADD_RESSOURCE_TYPE_REQUEST";
export const ADD_RESSOURCE_TYPE_SUCCESS = "ADD_RESSOURCE_TYPE_SUCCESS";
export const ADD_RESSOURCE_TYPE_FAILURE = "ADD_RESSOURCE_TYPE_FAILURE";

export const ADD_RESSOURCE_TYPE_TO_TABLE = "ADD_RESSOURCE_TYPE_TO_TABLE";
export const DELETE_RESSOURCE_TYPE_FROM_TABLE =
  "DELETE_RESSOURCE_TYPE_FROM_TABLE";

