export const FETCH_RESSOURCE_TYPES_REQUEST = "FETCH_RESSOURCE_TYPES_REQUEST";
export const FETCH_RESSOURCE_TYPES_SUCCESS = "FETCH_RESSOURCE_TYPES_SUCCESS";
export const FETCH_RESSOURCE_TYPES_FAILURE = "FETCH_RESSOURCE_TYPES_FAILURE";

export const UPDATE_RESSOURCE_TYPE_REQUEST = "UPDATE_RESSOURCE_TYPE_REQUEST";
export const UPDATE_RESSOURCE_TYPE_SUCCESS = "UPDATE_RESSOURCE_TYPE_SUCCESS";
export const UPDATE_RESSOURCE_TYPE_FAILURE = "UPDATE_RESSOURCE_TYPE_FAILURE";

export const DELETE_RESSOURCE_TYPE_REQUEST = "DELETE_RESSOURCE_TYPE_REQUEST";
export const DELETE_RESSOURCE_TYPE_SUCCESS = "DELETE_RESSOURCE_TYPE_SUCCESS";
export const DELETE_RESSOURCE_TYPE_FAILURE = "DELETE_RESSOURCE_TYPE_FAILURE";

export const ADD_RESSOURCE_TYPE_REQUEST = "ADD_RESSOURCE_TYPE_REQUEST";
export const ADD_RESSOURCE_TYPE_SUCCESS = "ADD_RESSOURCE_TYPE_SUCCESS";
export const ADD_RESSOURCE_TYPE_FAILURE = "ADD_RESSOURCE_TYPE_FAILURE";
