


export const FETCH_SPACE_REQUEST = "FETCH_SPACE_REQUEST";
export const FETCH_SPACE_SUCCESS = "FETCH_SPACE_SUCCESS";
export const FETCH_SPACE_FAILURE = "FETCH_SPACE_FAILURE";

export const UPDATE_SPACE_REQUEST = "UPDATE_SPACE_REQUEST";
export const UPDATE_SPACE_SUCCESS = "UPDATE_SPACE_SUCCESS";
export const UPDATE_SPACE_FAILURE = "UPDATE_SPACE_FAILURE";

export const DELETE_SPACE_REQUEST = "DELETE_SPACE_REQUEST";
export const DELETE_SPACE_SUCCESS = "DELETE_SPACE_SUCCESS";
export const DELETE_SPACE_FAILURE = "DELETE_SPACE_FAILURE";

export const ADD_SPACE_REQUEST = "ADD_SPACE_REQUEST";
export const ADD_SPACE_SUCCESS = "ADD_SPACE_SUCCESS";
export const ADD_SPACE_FAILURE = "ADD_SPACE_FAILURE";

export const ADD_SPACE_TO_TABLE = "ADD_SPACE_TO_TABLE";
export const DELETE_SPACE_FROM_TABLE =
  "DELETE_SPACE_FROM_TABLE";


export const ADD_ASSET_TO_SPACE_REQUEST = "ADD_ASSET_TO_SPACE_REQUEST";
export const ADD_ASSET_TO_SPACE_SUCCESS = "ADD_ASSET_TO_SPACE_SUCCESS";
export const ADD_ASSET_TO_SPACE_FAILURE = "ADD_ASSET_TO_SPACE_FAILURE";

export const REMOVE_ASSET_FROM_SPACE_REQUEST = "REMOVE_ASSET_FROM_SPACE_REQUEST";  
export const REMOVE_ASSET_FROM_SPACE_SUCCESS = "REMOVE_ASSET_FROM_SPACE_SUCCESS";  
export const REMOVE_ASSET_FROM_SPACE_FAILURE = "REMOVE_ASSET_FROM_SPACE_FAILURE";  

