export const ACTIVATE_USER_ACCOUNT_REQUEST = "ACTIVATE_USER_ACCOUNT_REQUEST";
export const ACTIVATE_USER_ACCOUNT_SUCCESS = "ACTIVATE_USER_ACCOUNT_SUCCESS";
export const ACTIVATE_USER_ACCOUNT_FAILURE = "ACTIVATE_USER_ACCOUNT_FAILURE";

export const FETCH_USERS_ACCOUNTS_REQUEST = "FETCH_USERS_ACCOUNTS_REQUEST";
export const FETCH_USERS_ACCOUNTS_SUCCESS = "FETCH_USERS_ACCOUNTS_SUCCESS";
export const FETCH_USERS_ACCOUNTS_FAILURE = "FETCH_USERS_ACCOUNTS_FAILURE";
