export const GET_ASSET_REQUEST = "GET_ASSET_REQUEST";
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS";
export const GET_ASSET_FAILURE = "GET_ASSET_FAILURE";

export const FETCH_ASSETS_REQUEST = "FETCH_ASSETS_REQUEST";
export const FETCH_ASSETS_SUCCESS = "FETCH_ASSETS_SUCCESS";
export const FETCH_ASSETS_FAILURE = "FETCH_ASSETS_FAILURE";

export const UPDATE_ASSET_REQUEST = "UPDATE_ASSET_REQUEST";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_FAILURE = "UPDATE_ASSET_FAILURE";

export const DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_FAILURE = "DELETE_ASSET_FAILURE";

export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_FAILURE = "ADD_ASSET_FAILURE";

export const ADD_ASSET_TO_TABLE = "ADD_ASSET_TO_TABLE";
export const UPDATE_ASSET_FROM_TABLE = "UPDATE_ASSET_FROM_TABLE";
export const DELETE_ASSET_FROM_TABLE = "DELETE_ASSET_FROM_TABLE";

export const FILL_ASSET_FORM = "FILL_ASSET_FORM";
export const EMPTY_ASSET_FORM = "EMPTY_ASSET_FORM";
